language: java
jdk:
  - oraclejdk8
script: "mvn cobertura:cobertura"
before_install:
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)
after_success:
  - bash <(curl -s https://codecov.io/bash) -t 5c4f891a-64ce-4986-be62-5b86ded543da
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r target/site/cobertura/coverage.xml -t 82249d5defba45cb8a3bd8ae69f72641